title: "Kaarthik Abhinav Balakrishnan"
description: "Computational neuroscience, BCIs, and curious experiments."
url: "https://kaarthik-balakrishnan.github.io"
baseurl: ""          # important for username.github.io
theme: minima        # use GitHub's built-in Jekyll theme

header_pages:
  - index.md
  - about.md
  - projects.md
  - publications.md
  - blog.md

exclude:
  - old_Projects